let itemsArray = [
  {
    name: "Waifu Body Pillow",
    url: "./assets/images/body-pillow.webp",
    category: "body-pillow anime",
    price: 30,
    rating: 3.4,
    id: 0,
  },
  {
    name: "500GB SSD",
    url: "./assets/images/ssd.webp",
    category: "computer storage ssd",
    price: 25.3,
    rating: 4.1,
    id: 1,
  },
  {
    name: "Waifu Body Pillow v2.0",
    url: "./assets/images/body-pillow.webp",
    category: "body-pillow anime",
    price: 50,
    rating: 2.1,
    id: 2,
  },
  {
    name: "Ganyu Figurine",
    url: "./assets/images/ganyu-figurine.webp",
    category: "figurine anime",
    price: 130,
    rating: 5.0,
    id: 3,
  },
  {
    name: "Keqing Figurine",
    url: "./assets/images/keqing-figurine.webp",
    category: "figurine anime",
    price: 125,
    rating: 4.8,
    id: 4,
  },
  {
    name: "RTX 3090",
    url: "./assets/images/rtx-3090.jpg",
    category: "computer gpu",
    price: 1300,
    rating: 2.0,
    id: 5,
  },
  {
    name: "RTX 4090",
    url: "./assets/images/rtx-4090.jpg",
    category: "computer gpu",
    price: 2000,
    rating: 3.6,
    id: 6,
  },
  {
    name: "RX 570",
    url: "./assets/images/rx-570.jpg",
    category: "computer gpu",
    price: 570,
    rating: 4.5,
    id: 7,
  },
  {
    name: "RX 580",
    url: "./assets/images/rx-580.jpg",
    category: "computer gpu",
    price: 600,
    rating: 4.3,
    id: 8,
  },
  {
    name: "Ryzen 5 1600",
    url: "./assets/images/cpu.jpg",
    category: "computer cpu",
    price: 350,
    rating: 3.2,
    id: 9,
  },
  {
    name: "Intel i5 6500",
    url: "./assets/images/cpu.jpg",
    category: "computer cpu",
    price: 400,
    rating: 4.5,
    id: 10,
  },
  {
    name: "Raiden Mei Figurine",
    url: "./assets/images/raiden-figurine.webp",
    category: "anime figurine",
    price: 135,
    rating: 4.2,
    id: 11,
  },
  {
    name: "Ryzen 7 1300X",
    url: "./assets/images/cpu.jpg",
    category: "computer cpu",
    price: 500,
    rating: 3.2,
    id: 12,
  },
  {
    name: "1TB SSD",
    url: "./assets/images/ssd.webp",
    category: "computer storage ssd",
    price: 150,
    rating: 4.9,
    id: 13,
  },
  {
    name: "2TB HDD",
    url: "./assets/images/hdd.webp",
    category: "computer storage hdd",
    price: 125,
    rating: 2.2,
    id: 14,
  },
  {
    name: "10TB HDD",
    url: "./assets/images/hdd.webp",
    category: "computer storage hdd",
    price: 228,
    rating: 3.9,
    id: 15,
  },
  {
    name: "4TB SSD",
    url: "./assets/images/ssd.webp",
    category: "computer storage ssd",
    price: 364,
    rating: 5.0,
    id: 16,
  },
  {
    name: "G.SKILL Aegis 16GB (2x8GB) DDR4 3200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 40,
    rating: 3.2,
    id: 17,
  },
  {
    name: "Kingston FURY Beast 16GB (2x8GB) DDR4 3200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 42,
    rating: 4.7,
    id: 18,
  },
  {
    name: "Kingston FURY Renegade 32GB (2x16GB) DDR4 3600MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 86,
    rating: 4.2,
    id: 19,
  },
  {
    name: "Kingston FURY Beast RGB 16GB (2x8GB) DDR4 3200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 62,
    rating: 3.5,
    id: 20,
  },
  {
    name: "Corsair VENGEANCE LPX 32GB (2x16GB) DDR4 3200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 70,
    rating: 4.2,
    id: 21,
  },
  {
    name: "Team Group DELTA RGB 32GB (2x16GB) DDR5 6200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 150,
    rating: 0,
    id: 22,
  },
  {
    name: "Kingston FURY Beast 64GB (2x32GB) DDR4 3200MHz",
    url: "./assets/images/ram.jpg",
    category: "computer ram",
    price: 120,
    rating: 0,
    id: 23,
  },
];

function getItems() {
  return itemsArray;
}

export default getItems;
